

export const CART_ACTION_TYPES = {
  SET_CART_VISIBLE: 'cart/SET_CART_VISIBLE',
  SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
  SET_CART_COUNT: 'cart/SET_CART_COUNT',
  SET_CART_TOTAL: 'cart/SET_CART_TOTAL',
};
